export const GET_ERRORS ='GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_CLASSROOM = 'GET_CLASSROOM';
export const CLASSROOM_LOADING = 'CLASSROOM_LOADING';
export const CLASSROOM_NOT_FOUND = 'CLASSROOM_NOT_FOUND';
export const CLEAR_CURRENT_CLASSROOM = 'CLEAR_CURRENT_CLASSROOM';
export const GET_CLASSROOMS = 'GET_CLASSROOMS';

export const GET_SUBJECT = 'GET_SUBJECT';
export const SUBJECT_LOADING = 'SUBJECT_LOADING';
export const SUBJECT_NOT_FOUND = 'SUBJECT_NOT_FOUND';
export const CLEAR_CURRENT_SUBJECT = 'CLEAR_CURRENT_SUBJECT';
export const GET_SUBJECTS = 'GET_SUBJECTS';

export const GET_CLASSNOTICE = 'GET_CLASSNOTICE';
export const CLASSNOTICE_LOADING = 'CLASSNOTICE_LOADING';
export const CLASSNOTICE_NOT_FOUND = 'CLASSNOTICE_NOT_FOUND';
export const CLEAR_CURRENT_CLASSNOTICE = 'CLEAR_CURRENT_CLASSNOTICE';
export const GET_CLASSNOTICESE = 'GET_CLASSROOMS_NOTICESE';

export const GET_SUBJECTNOTICE = 'GET_SUBJECTNOTICE';
export const SUBJECTNOTICE_LOADING = 'SUBJECTNOTICE_LOADING';
export const SUBJECTNOTICE_NOT_FOUND = 'SUBJECTNOTICE_NOT_FOUND';
export const CLEAR_CURRENT_SUBJECTNOTICE = 'CLEAR_CURRENT_SUBJECTNOTICE';
export const GET_SUBJECTNOTICESE = 'GET_SUBJECTROOMS_NOTICESE';

export const GET_NOTES = 'GET_NOTES';
export const NOTES_LOADING = 'NOTES_LOADING';
export const NOTES_NOT_FOUND = 'NOTES_NOT_FOUND';
export const CLEAR_CURRENT_NOTES = 'CLEAR_CURRENT_NOTES';
export const GET_ALLNOTES = 'GET_ALLNOTES';


export const DELETE_CLASSROOM = 'DELETE_CLASSROOM'